### PR TITLE
[HIGHLY UNSTABLE] Add preview function

### PR DESCRIPTION
**Pull request by Stoppedwumm**

### CODE REVIEW

**Comment by Stoppedwumm** [comment]
I‘m stopping work for today

**Comment by Stoppedwumm** [comment]
I literally updated the branch, how does it need another update

**Comment by Stoppedwumm** [comment]
Now it should work

**Comment by Stoppedwumm** [comment]
All updates for today done, see you tomorrow when fixing the 500 while searching. Pictures are complicated

**Comment by Stoppedwumm** [comment]
Small break, think about what I can fix

**Comment by StoppedwummSites** [comment]
This experiment is closing due to intern reworking

**Pull request closed without merging**
